"""Provides data acquisition and processing assets shared between Sun (NeuroAI) lab libraries.

See https://github.com/Sun-Lab-NBB/sl-shared-assets for more details.
API documentation: https://sl-shared-assets-api-docs.netlify.app/
Authors: Ivan Kondratyev (Inkaros), Kushaan Gupta, Natalie Yeung
"""

from ataraxis_base_utilities import console

from .data_classes import (
    RawData,
    DrugData,
    DatasetData,
    ImplantData,
    SessionData,
    SubjectData,
    SurgeryData,
    SessionTypes,
    TrackingData,
    InjectionData,
    ProcedureData,
    ProcessedData,
    ZaberPositions,
    DatasetTrackers,
    SessionMetadata,
    ManagingTrackers,
    ProcessingStatus,
    ProcessingTracker,
    DatasetSessionData,
    MesoscopePositions,
    ProcessingTrackers,
    DatasetTrackingData,
    ProcessingPipelines,
    RunTrainingDescriptor,
    LickTrainingDescriptor,
    MesoscopeHardwareState,
    WindowCheckingDescriptor,
    MesoscopeExperimentDescriptor,
)
from .configuration import (
    Cue,
    Segment,
    GasPuffTrial,
    TaskTemplate,
    VREnvironment,
    TrialStructure,
    MesoscopeCameras,
    WaterRewardTrial,
    AcquisitionSystems,
    MesoscopeFileSystem,
    ServerConfiguration,
    MesoscopeGoogleSheets,
    MesoscopeExternalAssets,
    MesoscopeExperimentState,
    MesoscopeMicroControllers,
    MesoscopeSystemConfiguration,
    MesoscopeExperimentConfiguration,
    get_working_directory,
    get_server_configuration,
    get_google_credentials_path,
    get_task_templates_directory,
    get_system_configuration_data,
    create_experiment_configuration,
)
from .data_transfer import (
    delete_directory,
    transfer_directory,
    calculate_directory_checksum,
)

# Ensures console is enabled when this library is imported.
if not console.enabled:
    console.enable()

__all__ = [
    "AcquisitionSystems",
    "Cue",
    "DatasetData",
    "DatasetSessionData",
    "DatasetTrackers",
    "DatasetTrackingData",
    "DrugData",
    "GasPuffTrial",
    "ImplantData",
    "InjectionData",
    "LickTrainingDescriptor",
    "ManagingTrackers",
    "MesoscopeCameras",
    "MesoscopeExperimentConfiguration",
    "MesoscopeExperimentDescriptor",
    "MesoscopeExperimentState",
    "MesoscopeExternalAssets",
    "MesoscopeFileSystem",
    "MesoscopeGoogleSheets",
    "MesoscopeHardwareState",
    "MesoscopeMicroControllers",
    "MesoscopePositions",
    "MesoscopeSystemConfiguration",
    "ProcedureData",
    "ProcessedData",
    "ProcessingPipelines",
    "ProcessingStatus",
    "ProcessingTracker",
    "ProcessingTrackers",
    "RawData",
    "RunTrainingDescriptor",
    "Segment",
    "ServerConfiguration",
    "SessionData",
    "SessionMetadata",
    "SessionTypes",
    "SubjectData",
    "SurgeryData",
    "TaskTemplate",
    "TrackingData",
    "TrialStructure",
    "VREnvironment",
    "WaterRewardTrial",
    "WindowCheckingDescriptor",
    "ZaberPositions",
    "calculate_directory_checksum",
    "create_experiment_configuration",
    "delete_directory",
    "get_google_credentials_path",
    "get_server_configuration",
    "get_system_configuration_data",
    "get_task_templates_directory",
    "get_working_directory",
    "transfer_directory",
]
