from enum import StrEnum
from pathlib import Path
from dataclasses import field, dataclass

from _typeshed import Incomplete
from ataraxis_data_structures import YamlConfig

class AcquisitionSystems(StrEnum):
    MESOSCOPE_VR = "mesoscope"

class StimulusTriggers(StrEnum):
    LICK = "lick"
    OCCUPANCY = "occupancy"
    COLLISION = "collision"

@dataclass()
class MesoscopeExperimentState:
    experiment_state_code: int
    system_state_code: int
    state_duration_s: float
    supported_trial_structures: list[str] | None = ...
    reinforcing_initial_guided_trials: int = ...
    reinforcing_recovery_failed_threshold: int = ...
    reinforcing_recovery_guided_trials: int = ...
    aversive_initial_guided_trials: int = ...
    aversive_recovery_failed_threshold: int = ...
    aversive_recovery_guided_trials: int = ...

@dataclass()
class _MesoscopeBaseTrial:
    cue_sequence: list[int]
    trial_length_cm: float
    stimulus_trigger_zone_start_cm: float
    stimulus_trigger_zone_end_cm: float
    stimulus_location_cm: float
    stimulus_trigger: str = ...
    stimulus_omission_trigger: str | None = ...
    def __post_init__(self) -> None: ...

@dataclass()
class WaterRewardTrial(_MesoscopeBaseTrial):
    reward_size_ul: float = ...
    reward_tone_duration_ms: int = ...

@dataclass()
class GasPuffTrial(_MesoscopeBaseTrial):
    puff_duration_ms: int = ...

@dataclass()
class MesoscopeExperimentConfiguration(YamlConfig):
    cue_map: dict[int, float]
    cue_offset_cm: float
    unity_scene_name: str
    experiment_states: dict[str, MesoscopeExperimentState]
    trial_structures: dict[str, WaterRewardTrial | GasPuffTrial]
    def __post_init__(self) -> None: ...

@dataclass()
class MesoscopeFileSystem:
    root_directory: Path = ...
    server_directory: Path = ...
    nas_directory: Path = ...
    mesoscope_directory: Path = ...

@dataclass()
class MesoscopeGoogleSheets:
    surgery_sheet_id: str = ...
    water_log_sheet_id: str = ...

@dataclass()
class MesoscopeCameras:
    face_camera_index: int = ...
    body_camera_index: int = ...
    face_camera_quantization: int = ...
    face_camera_preset: int = ...
    body_camera_quantization: int = ...
    body_camera_preset: int = ...

@dataclass()
class MesoscopeMicroControllers:
    actor_port: str = ...
    sensor_port: str = ...
    encoder_port: str = ...
    keepalive_interval_ms: int = ...
    minimum_brake_strength_g_cm: float = ...
    maximum_brake_strength_g_cm: float = ...
    wheel_diameter_cm: float = ...
    lick_threshold_adc: int = ...
    lick_signal_threshold_adc: int = ...
    lick_delta_threshold_adc: int = ...
    lick_averaging_pool_size: int = ...
    torque_baseline_voltage_adc: int = ...
    torque_maximum_voltage_adc: int = ...
    torque_sensor_capacity_g_cm: float = ...
    torque_report_cw: bool = ...
    torque_report_ccw: bool = ...
    torque_signal_threshold_adc: int = ...
    torque_delta_threshold_adc: int = ...
    torque_averaging_pool_size: int = ...
    wheel_encoder_ppr: int = ...
    wheel_encoder_report_cw: bool = ...
    wheel_encoder_report_ccw: bool = ...
    wheel_encoder_delta_threshold_pulse: int = ...
    wheel_encoder_polling_delay_us: int = ...
    cm_per_unity_unit: float = ...
    screen_trigger_pulse_duration_ms: int = ...
    sensor_polling_delay_ms: int = ...
    mesoscope_frame_averaging_pool_size = ...
    valve_calibration_data: dict[int | float, int | float] | tuple[tuple[int | float, int | float], ...] = ...

@dataclass()
class MesoscopeExternalAssets:
    headbar_port: str = ...
    lickport_port: str = ...
    wheel_port: str = ...
    unity_ip: str = ...
    unity_port: int = ...

@dataclass()
class MesoscopeSystemConfiguration(YamlConfig):
    name: str = ...
    filesystem: MesoscopeFileSystem = field(default_factory=MesoscopeFileSystem)
    sheets: MesoscopeGoogleSheets = field(default_factory=MesoscopeGoogleSheets)
    cameras: MesoscopeCameras = field(default_factory=MesoscopeCameras)
    microcontrollers: MesoscopeMicroControllers = field(default_factory=MesoscopeMicroControllers)
    assets: MesoscopeExternalAssets = field(default_factory=MesoscopeExternalAssets)
    def __post_init__(self) -> None: ...
    def save(self, path: Path) -> None: ...

@dataclass()
class ServerConfiguration(YamlConfig):
    username: str = ...
    password: str = ...
    host: str = ...
    storage_root: str = ...
    working_root: str = ...
    shared_directory_name: str = ...
    shared_storage_root: str = field(init=False, default_factory=Incomplete)
    shared_working_root: str = field(init=False, default_factory=Incomplete)
    user_data_root: str = field(init=False, default_factory=Incomplete)
    user_working_root: str = field(init=False, default_factory=Incomplete)
    def __post_init__(self) -> None: ...

def set_working_directory(path: Path) -> None: ...
def get_working_directory() -> Path: ...
def create_system_configuration_file(system: AcquisitionSystems | str) -> None: ...
def get_system_configuration_data() -> MesoscopeSystemConfiguration: ...
def set_google_credentials_path(path: Path) -> None: ...
def get_google_credentials_path() -> Path: ...
def create_server_configuration_file(
    username: str,
    password: str,
    host: str = "cbsuwsun.biopic.cornell.edu",
    storage_root: str = "/local/workdir",
    working_root: str = "/local/storage",
    shared_directory_name: str = "sun_data",
) -> None: ...
def get_server_configuration() -> ServerConfiguration: ...
