from enum import StrEnum
from pathlib import Path
from dataclasses import field, dataclass

from _typeshed import Incomplete
from ataraxis_data_structures import YamlConfig

from .configuration_data import (
    AcquisitionSystems as AcquisitionSystems,
    get_system_configuration_data as get_system_configuration_data,
)

class SessionTypes(StrEnum):
    LICK_TRAINING = "lick training"
    RUN_TRAINING = "run training"
    MESOSCOPE_EXPERIMENT = "mesoscope experiment"
    WINDOW_CHECKING = "window checking"

@dataclass()
class RawData:
    raw_data_path: Path = ...
    camera_data_path: Path = ...
    mesoscope_data_path: Path = ...
    behavior_data_path: Path = ...
    zaber_positions_path: Path = ...
    session_descriptor_path: Path = ...
    hardware_state_path: Path = ...
    surgery_metadata_path: Path = ...
    session_data_path: Path = ...
    experiment_configuration_path: Path = ...
    mesoscope_positions_path: Path = ...
    window_screenshot_path: Path = ...
    system_configuration_path: Path = ...
    checksum_path: Path = ...
    nk_path: Path = ...
    def resolve_paths(self, root_directory_path: Path) -> None: ...
    def make_directories(self) -> None: ...

@dataclass()
class ProcessedData:
    processed_data_path: Path = ...
    camera_data_path: Path = ...
    mesoscope_data_path: Path = ...
    behavior_data_path: Path = ...
    def resolve_paths(self, root_directory_path: Path) -> None: ...
    def make_directories(self) -> None: ...

@dataclass()
class TrackingData:
    tracking_data_path: Path = ...
    def resolve_paths(self, root_directory_path: Path) -> None: ...
    def make_directories(self) -> None: ...

@dataclass
class SessionData(YamlConfig):
    project_name: str
    animal_id: str
    session_name: str
    session_type: str | SessionTypes
    acquisition_system: str | AcquisitionSystems = ...
    experiment_name: str | None = ...
    python_version: str = ...
    sl_experiment_version: str = ...
    raw_data: RawData = field(default_factory=Incomplete)
    processed_data: ProcessedData = field(default_factory=Incomplete)
    tracking_data: TrackingData = field(default_factory=Incomplete)
    def __post_init__(self) -> None: ...
    @classmethod
    def create(
        cls,
        project_name: str,
        animal_id: str,
        session_type: SessionTypes | str,
        python_version: str,
        sl_experiment_version: str,
        experiment_name: str | None = None,
    ) -> SessionData: ...
    @classmethod
    def load(cls, session_path: Path) -> SessionData: ...
    def runtime_initialized(self) -> None: ...
    def save(self) -> None: ...
