from typing import Literal

from _typeshed import Incomplete

from ..configuration import (
    TaskTemplate as TaskTemplate,
    ServerConfiguration as ServerConfiguration,
    get_working_directory as get_working_directory,
    get_server_configuration as get_server_configuration,
    get_google_credentials_path as get_google_credentials_path,
    get_task_templates_directory as get_task_templates_directory,
)

mcp: Incomplete

def get_working_directory_tool() -> str: ...
def get_server_configuration_tool() -> str: ...
def get_google_credentials_tool() -> str: ...
def get_task_templates_directory_tool() -> str: ...
def list_available_templates_tool() -> str: ...
def get_template_info_tool(template_name: str) -> str: ...
def set_working_directory_tool(directory: str) -> str: ...
def set_google_credentials_tool(credentials_path: str) -> str: ...
def set_task_templates_directory_tool(directory: str) -> str: ...
def create_server_configuration_template_tool(
    username: str,
    host: str = "cbsuwsun.biohpc.cornell.edu",
    storage_root: str = "/local/storage",
    working_root: str = "/local/workdir",
    shared_directory: str = "sun_data",
) -> str: ...
def run_server(transport: Literal["stdio", "sse", "streamable-http"] = "stdio") -> None: ...
